version: "3"

services:
  kibana: 
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elastic:9200"
    depends_on:
      - elastic
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200